"""Generated from constants/councils.ts — do not edit by hand.

Regenerate with: python3 scripts/gen_councils.py
"""

COUNCILS = {
    "ACT": [
        "ACT Government"
    ],
    "NSW": [
        "Albury City Council",
        "Armidale Regional Council",
        "Ballina Shire Council",
        "Balranald Shire Council",
        "Bathurst Regional Council",
        "Bega Valley Shire Council",
        "Bellingen Shire Council",
        "Berrigan Shire Council",
        "Blacktown City Council",
        "Bland Shire Council",
        "Blayney Shire Council",
        "Blue Mountains City Council",
        "Bogan Shire Council",
        "Bourke Shire Council",
        "Brewarrina Shire Council",
        "Broken Hill City Council",
        "Byron Shire Council",
        "Cabonne Shire Council",
        "Camden Council",
        "Campbelltown City Council",
        "Canterbury-Bankstown Council",
        "Central Coast Council",
        "Central Darling Shire Council",
        "Cessnock City Council",
        "City of Sydney Council",
        "Clarence Valley Council",
        "Cobar Shire Council",
        "Coffs Harbour City Council",
        "Coolamon Shire Council",
        "Coonamble Shire Council",
        "Cootamundra-Gundagai Regional Council",
        "Cowra Shire Council",
        "Cumberland Council",
        "Dubbo Regional Council",
        "Dungog Shire Council",
        "Edward River Council",
        "Eurobodalla Shire Council",
        "Fairfield City Council",
        "Federation Council",
        "Forbes Shire Council",
        "Georges River Council",
        "Gilgandra Shire Council",
        "Glen Innes Severn Council",
        "Goulburn Mulwaree Council",
        "Greater Hume Shire Council",
        "Griffith City Council",
        "Gunnedah Shire Council",
        "Gwydir Shire Council",
        "Hawkesbury City Council",
        "Hay Shire Council",
        "Hilltops Council",
        "Hornsby Shire Council",
        "Hunter's Hill Council",
        "Inner West Council",
        "Inverell Shire Council",
        "Junee Shire Council",
        "Kempsey Shire Council",
        "Kiama Municipal Council",
        "Ku-ring-gai Council",
        "Kyogle Council",
        "Lachlan Shire Council",
        "Lake Macquarie City Council",
        "Lane Cove Municipal Council",
        "Leeton Shire Council",
        "Lismore City Council",
        "Lithgow City Council",
        "Liverpool City Council",
        "Liverpool Plains Shire Council",
        "Lockhart Shire Council",
        "Maitland City Council",
        "Mid-Coast Council",
        "Mid-Western Regional Council",
        "Moree Plains Shire Council",
        "Mosman Municipal Council",
        "Murray River Council",
        "Murrumbidgee Council",
        "Muswellbrook Shire Council",
        "Nambucca Valley Council",
        "Narrabri Shire Council",
        "Narrandera Shire Council",
        "Narromine Shire Council",
        "Newcastle City Council",
        "North Sydney Council",
        "Northern Beaches Council",
        "Oberon Council",
        "Orange City Council",
        "Parkes Shire Council",
        "Penrith City Council",
        "Port Macquarie-Hastings Council",
        "Port Stephens Council",
        "Queanbeyan-Palerang Regional Council",
        "Richmond Valley Council",
        "Ryde City Council",
        "Shellharbour City Council",
        "Shoalhaven City Council",
        "Singleton Council",
        "Snowy Monaro Regional Council",
        "Snowy Valleys Council",
        "Strathfield Municipal Council",
        "Sutherland Shire Council",
        "Tamworth Regional Council",
        "Temora Shire Council",
        "Tenterfield Shire Council",
        "The Hills Shire Council",
        "Tweed Shire Council",
        "Upper Hunter Shire Council",
        "Upper Lachlan Shire Council",
        "Uralla Shire Council",
        "Wagga Wagga City Council",
        "Walcha Council",
        "Walgett Shire Council",
        "Warren Shire Council",
        "Warrumbungle Shire Council",
        "Waverley Council",
        "Weddin Shire Council",
        "Wentworth Shire Council",
        "Willoughby City Council",
        "Wingecarribee Shire Council",
        "Wollondilly Shire Council",
        "Wollongong City Council",
        "Woollahra Municipal Council",
        "Yass Valley Council"
    ],
    "VIC": [
        "Alpine Shire Council",
        "Ararat Rural City Council",
        "Ballarat City Council",
        "Banyule City Council",
        "Bass Coast Shire Council",
        "Baw Baw Shire Council",
        "Bayside City Council",
        "Benalla Rural City Council",
        "Boroondara City Council",
        "Brimbank City Council",
        "Buloke Shire Council",
        "Campaspe Shire Council",
        "Cardinia Shire Council",
        "Casey City Council",
        "Central Goldfields Shire Council",
        "Colac Otway Shire Council",
        "Corangamite Shire Council",
        "Darebin City Council",
        "East Gippsland Shire Council",
        "Frankston City Council",
        "Gannawarra Shire Council",
        "Glen Eira City Council",
        "Glenelg Shire Council",
        "Golden Plains Shire Council",
        "Greater Bendigo City Council",
        "Greater Dandenong City Council",
        "Greater Geelong City Council",
        "Greater Shepparton City Council",
        "Hepburn Shire Council",
        "Hindmarsh Shire Council",
        "Hobsons Bay City Council",
        "Horsham Rural City Council",
        "Hume City Council",
        "Indigo Shire Council",
        "Kingston City Council",
        "Knox City Council",
        "Latrobe City Council",
        "Loddon Shire Council",
        "Macedon Ranges Shire Council",
        "Manningham City Council",
        "Mansfield Shire Council",
        "Maribyrnong City Council",
        "Maroondah City Council",
        "Melbourne City Council",
        "Melton City Council",
        "Merri-bek City Council",
        "Mildura Rural City Council",
        "Mitchell Shire Council",
        "Moira Shire Council",
        "Monash City Council",
        "Moonee Valley City Council",
        "Moorabool Shire Council",
        "Mornington Peninsula Shire Council",
        "Mount Alexander Shire Council",
        "Moyne Shire Council",
        "Murrindindi Shire Council",
        "Nillumbik Shire Council",
        "Northern Grampians Shire Council",
        "Port Phillip City Council",
        "Pyrenees Shire Council",
        "Queenscliffe Borough Council",
        "South Gippsland Shire Council",
        "Southern Grampians Shire Council",
        "Stonnington City Council",
        "Strathbogie Shire Council",
        "Surf Coast Shire Council",
        "Swan Hill Rural City Council",
        "Towong Shire Council",
        "Wangaratta Rural City Council",
        "Warrnambool City Council",
        "Wellington Shire Council",
        "West Wimmera Shire Council",
        "Whitehorse City Council",
        "Whittlesea City Council",
        "Wodonga City Council",
        "Wyndham City Council",
        "Yarra City Council",
        "Yarra Ranges Shire Council",
        "Yarriambiack Shire Council"
    ],
    "QLD": [
        "Aurukun Shire Council",
        "Balonne Shire Council",
        "Banana Shire Council",
        "Barcaldine Regional Council",
        "Barcoo Shire Council",
        "Blackall-Tambo Regional Council",
        "Boulia Shire Council",
        "Brisbane City Council",
        "Bulloo Shire Council",
        "Bundaberg Regional Council",
        "Cairns Regional Council",
        "Carpentaria Shire Council",
        "Cassowary Coast Regional Council",
        "Central Highlands Regional Council",
        "Charters Towers Regional Council",
        "Cloncurry Shire Council",
        "Cook Shire Council",
        "Croydon Shire Council",
        "Diamantina Shire Council",
        "Doomadgee Aboriginal Shire Council",
        "Douglas Shire Council",
        "Etheridge Shire Council",
        "Flinders Shire Council",
        "Fraser Coast Regional Council",
        "Gold Coast City Council",
        "Goondiwindi Regional Council",
        "Gympie Regional Council",
        "Hinchinbrook Shire Council",
        "Ipswich City Council",
        "Isaac Regional Council",
        "Lockyer Valley Regional Council",
        "Logan City Council",
        "Longreach Regional Council",
        "Mackay Regional Council",
        "Maranoa Regional Council",
        "Mareeba Shire Council",
        "McKinlay Shire Council",
        "Moreton Bay Regional Council",
        "Mornington Shire Council",
        "Mount Isa City Council",
        "Murweh Shire Council",
        "Napranum Aboriginal Shire Council",
        "Noosa Shire Council",
        "North Burnett Regional Council",
        "Northern Peninsula Area Regional Council",
        "Palm Island Aboriginal Shire Council",
        "Paroo Shire Council",
        "Quilpie Shire Council",
        "Redland City Council",
        "Richmond Shire Council",
        "Rockhampton Regional Council",
        "Scenic Rim Regional Council",
        "Somerset Regional Council",
        "South Burnett Regional Council",
        "Sunshine Coast Council",
        "Tablelands Regional Council",
        "Toowoomba Regional Council",
        "Torres Shire Council",
        "Torres Strait Island Regional Council",
        "Townsville City Council",
        "Western Downs Regional Council",
        "Whitsunday Regional Council",
        "Winton Shire Council",
        "Woorabinda Aboriginal Shire Council",
        "Yarrabah Aboriginal Shire Council"
    ],
    "SA": [
        "Adelaide City Council",
        "Adelaide Hills Council",
        "Alexandrina Council",
        "Barossa Council",
        "Barunga West District Council",
        "Burnside City Council",
        "Campbelltown City Council",
        "Ceduna District Council",
        "Charles Sturt City Council",
        "Clare & Gilbert Valleys Council",
        "Cleve District Council",
        "Coober Pedy District Council",
        "Copper Coast District Council",
        "Elliston District Council",
        "Flinders Ranges Council",
        "Franklin Harbour District Council",
        "Gawler Town Council",
        "Goyder Regional Council",
        "Grant District Council",
        "Holdfast Bay City Council",
        "Kangaroo Island Council",
        "Karoonda East Murray District Council",
        "Kimba District Council",
        "Kingston District Council",
        "Light Regional Council",
        "Lower Eyre Peninsula District Council",
        "Loxton Waikerie District Council",
        "Mallala District Council",
        "Marion City Council",
        "Mid Murray Council",
        "Mitcham City Council",
        "Mount Barker District Council",
        "Mount Gambier City Council",
        "Mount Remarkable District Council",
        "Murray Bridge Rural City Council",
        "Naracoorte Lucindale Council",
        "Northern Areas Council",
        "Norwood Payneham & St Peters City Council",
        "Onkaparinga City Council",
        "Orroroo Carrieton District Council",
        "Peterborough District Council",
        "Port Adelaide Enfield City Council",
        "Port Augusta City Council",
        "Port Lincoln City Council",
        "Port Pirie Regional Council",
        "Prospect City Council",
        "Renmark Paringa Council",
        "Robe District Council",
        "Roxby Downs Municipal Council",
        "Salisbury City Council",
        "Southern Mallee District Council",
        "Streaky Bay District Council",
        "Tatiara District Council",
        "Tea Tree Gully City Council",
        "Tumby Bay District Council",
        "Unley City Council",
        "Victor Harbor City Council",
        "Wakefield Regional Council",
        "Walkerville Town Council",
        "Wattle Range Council",
        "West Torrens City Council",
        "Whyalla City Council",
        "Wudinna District Council",
        "Yankalilla District Council",
        "Yorke Peninsula Council"
    ],
    "WA": [
        "Albany City",
        "Armadale City",
        "Ashburton Shire",
        "Augusta-Margaret River Shire",
        "Bassendean Town",
        "Bayswater City",
        "Belmont City",
        "Beverley Shire",
        "Boddington Shire",
        "Boyup Brook Shire",
        "Bridgetown-Greenbushes Shire",
        "Brookton Shire",
        "Broome Shire",
        "Broomehill-Tambellup Shire",
        "Bruce Rock Shire",
        "Bunbury City",
        "Busselton City",
        "Cambridge Town",
        "Canning City",
        "Capel Shire",
        "Carnamah Shire",
        "Carnarvon Shire",
        "Chapman Valley Shire",
        "Chittering Shire",
        "Claremont Town",
        "Cockburn City",
        "Collie Shire",
        "Coolgardie Shire",
        "Coorow Shire",
        "Corrigin Shire",
        "Cottesloe Town",
        "Cranbrook Shire",
        "Cuballing Shire",
        "Cue Shire",
        "Cunderdin Shire",
        "Dalwallinu Shire",
        "Dandaragan Shire",
        "Dardanup Shire",
        "Denmark Shire",
        "Derby-West Kimberley Shire",
        "Donnybrook-Balingup Shire",
        "Dowerin Shire",
        "Dumbleyung Shire",
        "Dundas Shire",
        "East Fremantle Town",
        "East Pilbara Shire",
        "Esperance Shire",
        "Exmouth Shire",
        "Fremantle City",
        "Gingin Shire",
        "Gnowangerup Shire",
        "Goomalling Shire",
        "Gosnells City",
        "Greater Geraldton City",
        "Halls Creek Shire",
        "Harvey Shire",
        "Irwin Shire",
        "Jerramungup Shire",
        "Joondalup City",
        "Kalamunda City",
        "Kalgoorlie-Boulder City",
        "Karratha City",
        "Katanning Shire",
        "Kellerberrin Shire",
        "Kent Shire",
        "Kojonup Shire",
        "Kondinin Shire",
        "Koorda Shire",
        "Kulin Shire",
        "Lake Grace Shire",
        "Laverton Shire",
        "Leonora Shire",
        "Mandurah City",
        "Manjimup Shire",
        "Meekatharra Shire",
        "Melville City",
        "Merredin Shire",
        "Mingenew Shire",
        "Moora Shire",
        "Morawa Shire",
        "Mount Magnet Shire",
        "Mount Marshall Shire",
        "Moyne Shire",
        "Mukinbudin Shire",
        "Mundaring Shire",
        "Murchison Shire",
        "Murray Shire",
        "Nannup Shire",
        "Narembeen Shire",
        "Narrogin City",
        "Narrogin Shire",
        "Nedlands City",
        "Ngaanyatjarraku Shire",
        "Northam City",
        "Northampton Shire",
        "Nungarin Shire",
        "Peppermint Grove Town",
        "Perenjori Shire",
        "Perth City",
        "Pingelly Shire",
        "Plantagenet Shire",
        "Port Hedland Town",
        "Quairading Shire",
        "Ravensthorpe Shire",
        "Rockingham City",
        "Sandstone Shire",
        "Serpentine-Jarrahdale Shire",
        "Shark Bay Shire",
        "South Perth City",
        "Stirling City",
        "Subiaco City",
        "Swan City",
        "Tammin Shire",
        "Three Springs Shire",
        "Toodyay Shire",
        "Trayning Shire",
        "Upper Gascoyne Shire",
        "Victoria Park Town",
        "Victoria Plains Shire",
        "Vincent City",
        "Wagin Shire",
        "Wandering Shire",
        "Waroona Shire",
        "Warren-Blackwood Shire",
        "West Arthur Shire",
        "Westonia Shire",
        "Wickepin Shire",
        "Williams Shire",
        "Wiluna Shire",
        "Wongan-Ballidu Shire",
        "Woodanilling Shire",
        "Wyalkatchem Shire",
        "Wyndham-East Kimberley Shire",
        "Yalgoo Shire",
        "Yilgarn Shire",
        "York Shire"
    ],
    "TAS": [
        "Break O'Day Council",
        "Brighton Council",
        "Burnie City Council",
        "Central Coast Council",
        "Central Highlands Council",
        "Circular Head Council",
        "Clarence City Council",
        "Derwent Valley Council",
        "Dorset Council",
        "Flinders Council",
        "George Town Council",
        "Glenorchy City Council",
        "Hobart City Council",
        "Huon Valley Council",
        "Kentish Council",
        "King Island Council",
        "Kingborough Council",
        "Latrobe Council",
        "Launceston City Council",
        "Meander Valley Council",
        "Northern Midlands Council",
        "Sorell Council",
        "Southern Midlands Council",
        "Tasman Council",
        "Waratah-Wynyard Council",
        "West Coast Council",
        "West Tamar Council"
    ],
    "NT": [
        "Alice Springs Town Council",
        "Barkly Regional Council",
        "Belyuen Community Government Council",
        "Central Desert Regional Council",
        "Coomalie Community Government Council",
        "Darwin City Council",
        "East Arnhem Regional Council",
        "Katherine Town Council",
        "Litchfield Council",
        "MacDonnell Regional Council",
        "Palmerston City Council",
        "Roper Gulf Regional Council",
        "Tiwi Islands Regional Council",
        "Victoria Daly Regional Council",
        "Wagait Shire Council",
        "West Arnhem Regional Council",
        "West Daly Regional Council"
    ]
}
