default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|
    track = options[:track] || 'alpha'
    
    upload_to_play_store(
      track: track,
      aab: "app/build/outputs/bundle/release/app-release.aab",
      release_status: "draft"
    )
  end
end
